### ISSUE TITLE
Magnificent extension,please maintain it

### ISSUE THREAD

**Issue by IvanDeFelice76** [eugene-rom/discrete-brightness#3]
Magnificent extension, please keep it..I tried other similar ones but none was done so well and often conflicted with others...I'm using it on Fedora 33 since I have problems with light sensitivity having light eyes and being allergic and I really owe you a "Thank you" for the great work, I hope you will update it constantly so I can always use it!

**Comment by eugene-rom** [comment]
Thank you, @xzj8b3 !
